env: "dev" # local, dev, prod
http_server:
  address: "0.0.0.0:8081"
  timeout: "4s" # время на принятие запроса и отправку ответа
  idle_timeout: "30s" # время простоя соединения
  stop_timeout: "10s" # время, через которое выключится сервер после получения SIGINT в случае наличия активных соединений
  rate limit:
    limit: 50
    interval: "1s" 
    msg: "Слишком много запросов."

# отрицательный лимит - отказ всегда,
# нулевой лимит - лимита нет,
# установил это экспериментально, в документации по go-chi/httprate об этом нет